# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    # Chef Server - CentOS Stream 8
    config.vm.define "server" do |server|
        server.vm.box = "shekeriev/centos-stream-8"
        server.vm.hostname = "chef-server"
        server.vm.network "private_network", ip: "192.168.99.101"
        server.vm.provision "shell", path: "add_hosts.sh"
        server.vm.provision "shell", path: "install_ntp_redhat.sh"
        server.vm.provision "shell", path: "install_chef_server.sh"
        server.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 4096
            v.cpus = 1
        end
    end

    # Chef Client #1 - Debian 11
    config.vm.define "docker" do |docker|
        docker.vm.box = "shekeriev/debian-11"
        docker.vm.hostname = "docker-host"
        docker.vm.network "private_network", ip: "192.168.99.102"
        docker.vm.provision "shell", path: "add_hosts.sh"
        docker.vm.provision "shell", path: "install_ntp_debian.sh"
        docker.vm.provision "shell", path: "copy_web_and_db.sh"
        docker.vm.provision "shell", path: "install_docker_debian.sh"
        docker.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 512
            v.cpus = 1
        end
    end
  
    # Chef Workstation - CentOS 8.x
    config.vm.define "workstation" do |workstation|
        workstation.vm.box = "shekeriev/centos-stream-8"
        workstation.vm.hostname = "chef-wrkstn"
        workstation.vm.network "private_network", ip: "192.168.99.103"
        workstation.vm.provision "shell", path: "add_hosts.sh"
        workstation.vm.provision "shell", path: "install_ntp_redhat.sh"
        workstation.vm.provision "shell", path: "install_chef_workstation.sh"
        workstation.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 2048
            v.cpus = 1
        end
    end
  
end
