# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false

    config.vm.define "db" do |db|
        db.vm.box = "shekeriev/debian-11"
        db.vm.hostname = "db.do2.lab"
        db.vm.network "private_network", ip: "192.168.99.101"
        db.vm.network "forwarded_port", guest: 80, host: 8081
        db.vm.provision "shell", path: "add_hosts.sh"
        db.vm.provision "shell", path: "copy_mysql_database.sh"
        db.vm.provision "shell", path: "install_and_setup_salt_minion.sh"
        db.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
    end

    config.vm.define "web" do |web|
        web.vm.box = "shekeriev/centos-stream-8"
        web.vm.hostname = "web.do2.lab"
        web.vm.network "private_network", ip: "192.168.99.100"
        web.vm.network "forwarded_port", guest: 80, host: 8080
        web.vm.provision "shell", path: "add_hosts.sh"
        web.vm.provision "shell", path: "install_salt_master.sh"
        web.vm.provision "shell", path: "install_apache_php.sh"
        web.vm.provision "shell", path: "setup_salt_master.sh"
        web.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
    end

end
