# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    # Puppet Server - CentOS Stream 8
    config.vm.define "server" do |server|
        server.vm.box = "shekeriev/centos-stream-8"
        server.vm.hostname = "puppet-server"
        server.vm.network "private_network", ip: "192.168.99.100"
        server.vm.provision "shell", path: "add_hosts.sh"
        server.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 2048
            v.cpus = 1
        end
    end

    # Puppet Client #1 - CentOS Stream 8
    config.vm.define "client1" do |client1|
        client1.vm.box = "shekeriev/centos-stream-8"
        client1.vm.hostname = "puppet-client-1"
        client1.vm.network "private_network", ip: "192.168.99.101"
        client1.vm.provision "shell", path: "add_hosts.sh"
        client1.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 512
            v.cpus = 1
        end
    end

    # Puppet Client #2 - CentOS Stream 8
    config.vm.define "client2" do |client2|
        client2.vm.box = "shekeriev/centos-stream-8"
        client2.vm.hostname = "puppet-client-2"
        client2.vm.network "private_network", ip: "192.168.99.102"
        client2.vm.provision "shell", path: "add_hosts.sh"
        client2.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 512
            v.cpus = 1
        end
    end

    # # Puppet Client #2 - Debian 11
    # config.vm.define "client2" do |client2|
    #     client2.vm.box = "shekeriev/debian-11"
    #     client2.vm.hostname = "puppet-client-2"
    #     client2.vm.network "private_network", ip: "192.168.99.102"
    #     client2.vm.provision "shell", path: "add_hosts.sh"
    #     client2.vm.provider "virtualbox" do |v|
        #     v.gui = false
        #     v.memory = 512
        #     v.cpus = 1
    #     end
    # end
  
end
