# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    # Apache Kafka Machine - CentOS Stream 8
    config.vm.define "kafka" do |kafka|
        kafka.vm.box = "shekeriev/centos-stream-8"
        kafka.vm.hostname = "kafka"
        kafka.vm.network "private_network", ip: "192.168.99.101"
        kafka.vm.provision "shell", path: "add_hosts.sh"
        kafka.vm.provision "shell", path: "install_kafka.sh", privileged: false
        kafka.vm.provision "shell", path: "install_python.sh", privileged: false
        kafka.vm.provision "shell", path: "run_kafka.sh", privileged: false
        kafka.vm.provision "shell", path: "run_kafka_exporter.sh", privileged: false
        kafka.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 2048
            v.cpus = 1
        end
    end
    
    # Monitoring Machine - CentOS Stream 8
    config.vm.define "monitor" do |monitor|
        monitor.vm.box = "shekeriev/centos-stream-8"
        monitor.vm.hostname = "monitor"
        monitor.vm.network "private_network", ip: "192.168.99.102"
        monitor.vm.provision "shell", path: "add_hosts.sh"
        monitor.vm.provision "shell", path: "install_and_run_promgraf.sh"
        monitor.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 1024
            v.cpus = 1
        end
    end

end
