# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    # Apache Kafka Machines - CentOS Stream 8
    config.vm.box = "shekeriev/centos-stream-8"
    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = 2048
        v.cpus = 1
    end
    (1..3).each do |i|
        config.vm.define "kafka-#{i}" do |kafka|
            kafka.vm.hostname = "kafka-#{i}"
            kafka.vm.network "private_network", ip: "192.168.99.10#{i}"
            kafka.vm.provision "shell", path: "add_hosts.sh"
        end
    end
    
    # Monitoring Machine - CentOS Stream 8
    config.vm.define "monitoring" do |monitoring|
        monitoring.vm.hostname = "monitoring"
        monitoring.vm.network "private_network", ip: "192.168.99.104"
        monitoring.vm.provision "shell", path: "add_hosts.sh"
    end

end
