# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.box = "shekeriev/debian-11"
    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = 2048
        v.cpus = 1
    end

    # Apache Kafka Machines - Debian 11
    (1..3).each do |i|
        config.vm.define "kafka-#{i}" do |kafka|
        kafka.vm.hostname = "kafka-#{i}"
        kafka.vm.network "private_network", ip: "192.168.98.10#{i}"
        kafka.vm.provision "shell", path: "add_hosts.sh"
        end
    end
    
    # Monitoring Machine - Debian 11
    config.vm.define "monitoring" do |monitoring|
        monitoring.vm.hostname = "monitoring"
        monitoring.vm.network "private_network", ip: "192.168.98.104"
        monitoring.vm.provision "shell", path: "add_hosts.sh"
    end

end
