# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false

    config.vm.define "docker" do |docker|
        docker.vm.box = "shekeriev/debian-11"
        docker.vm.hostname = "docker"
        docker.vm.network "private_network", ip: "192.168.99.100"
        docker.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
        docker.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
        docker.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
        docker.vm.provision "shell", path: "install_and_config_docker.sh"
    end

end
